#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'home.html.twig'